apiVersion: batch/v1
kind: Job
metadata:
  name: vq-vae-speech
spec:
  template:
    spec:
      containers:
      - name: skelter-tf1.13-speech
        image: skelter/tensorflow-speech:1.13-gpu-ubuntu18.04
        imagePullPolicy: Always
        resources:
          limits:
            nvidia.com/gpu: "1"
            memory: "8G"
          requests:
            nvidia.com/gpu: "1"
            memory: "5G"
        volumeMounts:
        - mountPath: /nas0
          name: nas0
        workingDir: /nas0/home/jonghoon.seo/vqvae-speech
        command: [
          "python",
          "wav2tfr.py",
          "--fs=16000",
          "--output_dir=dataset/VCTK/tfr",
          "--speaker_list=etc/speakers.tsv",
          "--file_pattern=dataset/VCTK/wav48/*/*.wav"
        ]
      volumes:
          - hostPath:
              path: /nas0
            name: nas0
      restartPolicy: Never
      imagePullSecrets:
      - name: docker-cred
